[platformio]
default_envs = waveshare_epaper_154_v2
src_dir = firmware/src
include_dir = firmware/include

[env:waveshare_epaper_154_v2]
platform = espressif32@6.11.0
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 8MB

board_build.partitions = firmware/partitions.csv

board_build.embed_txtfiles =
    firmware/certs/README.txt

board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS="firmware/sdkconfig.defaults"

build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3

monitor_filters =
    esp32_exception_decoder