import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync(new URL('../src/web/app.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../src/web/index.html', import.meta.url), 'utf8');
assert.match(html, /<dialog id="access-dialog"[^>]*aria-labelledby="pin-title"/);
assert.match(html, /id="token"[^>]*inputmode="numeric"[^>]*pattern="\[0-9\]\{6\}"[^>]*maxlength="6"[^>]*minlength="6"/);
const elements = new Map();
function element(id) {
  if (!elements.has(id)) elements.set(id, {textContent:'',value:'',disabled:false,hidden:false,dataset:{},
    focus(){}, showModal(){this.open=true;}, close(){this.open=false; if(this.closeEvent)this.closeEvent();}, addEventListener(name, fn) { this[name === 'close' ? 'closeEvent' : name] = fn; }, setAttribute(name,value) {this[name]=value;}});
  return elements.get(id);
}
let requests = [], response = {state:'idle',wifi:true,ip:'192.168.1.4',pending:2,text:'<script>safe</script>',live_text:'',note_id:'note',stopping:false,recovery:false,command_busy:false,command_id:0,command_result:''};
const context = vm.createContext({document:{getElementById:element},fetch:async (url,options)=>{
  requests.push([url, options]); return {ok:true,status:200,json:async()=>response};
},AbortSignal:{timeout:()=>null},setTimeout:()=>0,clearTimeout(){}});
vm.runInContext(source, context);
assert.equal(element('record').disabled,true);
element('open-access').click();
assert.equal(element('access-dialog').open,true);
element('token').value='12345';
await element('access').submit({preventDefault(){}});
assert.equal(requests.length,0,'invalid PIN must never reach the API');
element('cancel-access').click();
assert.equal(element('token').value,'');
element('token').value='001234';
await element('access').submit({preventDefault(){}});
assert.equal(requests[0][1].headers.Authorization,'Bearer 001234');
assert.equal(element('text').textContent,'<script>safe</script>');
assert.equal(element('record').disabled,false);
assert.equal(element('sync').disabled,false);
response={id:1}; await element('record').click();
assert.equal(requests.at(-1)[0],'/api/command/start');
assert.match(element('message').textContent,/waiting/i);
assert.equal(element('record').disabled,true);
response={state:'idle',wifi:true,pending:1,stopping:false,recovery:false,command_busy:false,command_id:2,command_result:'ok'};
await vm.runInContext('refresh()', context);
assert.equal(element('record').disabled,false, 'another client must not leave our UI stuck waiting for an overwritten result');
assert.match(element('message').textContent,/another session/i);
context.fetch = async()=>{throw Error('offline');};
await vm.runInContext('refresh()', context);
assert.equal(element('record').disabled,true);
assert.match(element('message').textContent,/connection/i);
context.fetch=async()=>({ok:true,status:200,json:async()=>response});
await vm.runInContext('refresh()', context);
assert.equal(element('record').disabled,false);
assert.match(element('message').textContent,/restored/i);
element('disconnect').click();
element('open-access').click();
context.fetch=async()=>({ok:false,status:401,json:async()=>({error:'pin_attempts_exhausted'})});
element('token').value='111111'; await element('access').submit({preventDefault(){}});
assert.equal(element('access-dialog').open,true);
assert.match(element('access-message').textContent,/Five incorrect PIN attempts.*reopen/);
assert.equal(element('token').value,'');
context.fetch=async url=>({ok:url!='/api/notes',status:url==='/api/notes'?503:200,json:async()=>response});
element('token').value='001234'; await element('access').submit({preventDefault(){}});
assert.equal(element('record').disabled,true,'failed private load must not unlock controls');
assert.equal(element('text').textContent,'');
let releaseOld, releaseNew;
context.fetch=async()=>new Promise(resolve=>{releaseOld=resolve;});
element('token').value='001234'; const oldLogin=element('access').submit({preventDefault(){}});
await new Promise(resolve=>setImmediate(resolve));
element('cancel-access').click(); element('open-access').click();
context.fetch=async url=>url==='/api/status'?new Promise(resolve=>{releaseNew=resolve;}):({ok:true,status:200,json:async()=>response});
element('token').value='001234'; const newLogin=element('access').submit({preventDefault(){}});
await new Promise(resolve=>setImmediate(resolve));
releaseOld({ok:false,status:401,json:async()=>({error:'pin_attempts_exhausted'})}); await oldLogin;
assert.equal(element('access-button').disabled,true,'stale login cannot unlock a newer pending attempt');
assert.equal(element('access-message').textContent,'Connecting…');
releaseNew({ok:true,status:200,json:async()=>response}); await newLogin;
assert.equal(element('access-dialog').open,false);
console.log('web UI PIN modal, exhaustion, stale pairing, failed-load lock, safe text, queued-not-success, offline: PASS');
