import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const elements = new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{value:'',textContent:'',dataset:{},disabled:false,hidden:false,focus(){},showModal(){this.open=true;},close(){this.open=false; if(this.closeEvent)this.closeEvent();},addEventListener(k,v){this[k === 'close' ? 'closeEvent' : k]=v;},setAttribute(k,v){this[k]=v;}});return elements.get(id);};
let status={state:'idle',wifi:true,ip:'192.168.1.4',pending:0,command_id:0,command_result:'',command_busy:false};
let config={base_url:'http://192.168.1.20:8000',command_id:0,command_result:'',command_busy:false};
let requests=[],code=200;
const context=vm.createContext({document:{getElementById:el},AbortSignal:{timeout:()=>null},setTimeout:()=>0,clearTimeout(){},fetch:async(path,options)=>{requests.push([path,options]);return {ok:code<400,status:code,json:async()=> options.method==='POST'?{id:1,status:'queued'}:path==='/api/status'?status:config};}});
vm.runInContext(fs.readFileSync(new URL('../src/web/app.js',import.meta.url),'utf8'),context);
el('token').value='001234'; await el('access').submit({preventDefault(){}});
assert.equal(el('server-url').value,config.base_url,'unlock loads authenticated server URL');
el('server-url').value='http://192.168.1.21:8001';
await vm.runInContext('refresh()',context); assert.equal(el('server-url').value,'http://192.168.1.21:8001','status poll preserves editing');
await el('server-config').submit({preventDefault(){}});
assert.equal(requests.at(-1)[0],'/api/config/server');
assert.deepEqual(JSON.parse(requests.at(-1)[1].body),{base_url:'http://192.168.1.21:8001'});
assert.match(el('message').textContent,/waiting/i);
status={...status,command_id:1,command_result:'failed'};
await vm.runInContext('refresh()',context); assert.match(el('message').textContent,/not saved/i);
await el('server-config').submit({preventDefault(){}});
status={...status,command_result:'ok'};
await vm.runInContext('refresh()',context); assert.match(el('message').textContent,/not confirmed/i,'ok with wrong URL must not claim success');
await el('server-config').submit({preventDefault(){}});
config={...config,base_url:'http://192.168.1.21:8001',server_revision:1,command_id:1,command_result:'ok'};
await vm.runInContext('refresh()',context); assert.match(el('message').textContent,/saved/i);
el('server-token').value='runtime-secret';
await el('server-config').submit({preventDefault(){}});
assert.equal(JSON.parse(requests.at(-1)[1].body).token,'runtime-secret');
assert.equal(el('server-token').value,'');
config={...config,server_revision:2,token_configured:true};
await vm.runInContext('refresh()',context); assert.match(el('message').textContent,/saved/i);
for(const bad of ['http://127.0.0.1','http://0.0.0.0','http://224.0.0.1','http://192.168.1.4:8000','http://192.168.1.20/path','http://a@192.168.1.20','http://192.168.1.20:0']) {
 el('server-url').value=bad; const n=requests.length; await el('server-config').submit({preventDefault(){}}); assert.equal(requests.length,n);
}
code=401; await vm.runInContext('refresh()',context);
assert.equal(el('server-url').value,''); assert.equal(el('token').value,''); assert.equal(el('text').textContent,''); assert.equal(el('server-panel').hidden,false);
code=200;
el('token').value='001234'; await el('access').submit({preventDefault(){}});
let releaseStatus;
const fetchNormal=context.fetch;
context.fetch=async(path,options)=>path==='/api/status'?{ok:true,status:200,json:()=>new Promise(resolve=>{releaseStatus=resolve;})}:fetchNormal(path,options);
el('server-url').value='http://192.168.1.21:8001';
const oldPoll=vm.runInContext('refresh()',context); await new Promise(resolve=>setImmediate(resolve));
await el('server-config').submit({preventDefault(){}});
releaseStatus({...status,command_id:0,command_result:''}); await oldPoll;
assert.equal(el('save-server').disabled,true,'a status poll started before enqueue must not lose the pending save');
context.fetch=fetchNormal;
await vm.runInContext('refresh()',context);
let releaseBody;
context.fetch=async(path)=>({ok:true,status:200,json:()=>path==='/api/status'?new Promise(resolve=>{releaseBody=resolve;}):Promise.resolve(config)});
const late=vm.runInContext('refresh()',context); await new Promise(resolve=>setImmediate(resolve));
await el('disconnect').click(); releaseBody(status); await late;
assert.equal(el('text').textContent,'','late JSON after logout must not repopulate private data');
assert.equal(el('server-panel').hidden,false);
assert.match(el('message').textContent,/Disconnected/,'late response must not overwrite logout status');
console.log('PASS web server settings unlock/edit/queued failure/exact readback/validation/401 clearing');
