import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../src/web/index.html',import.meta.url),'utf8');
assert.match(html,/id="settings-nav"/,'Settings must be reachable from navigation');
const elements=new Map();
const el=id=>{if(!elements.has(id)) elements.set(id,{value:'',checked:false,textContent:'',dataset:{},disabled:false,hidden:false,focus(){},showModal(){this.open=true;},close(){this.open=false; if(this.closeEvent)this.closeEvent();},addEventListener(k,v){this[k === 'close' ? 'closeEvent' : k]=v;},setAttribute(k,v){this[k]=v;}});return elements.get(id);};
let state={state:'idle',wifi:true,ip:'192.168.1.4',pending:0,command_id:0,command_result:'',command_busy:false,mounted:true};
let settings={home_ssid:'home',hotspot_ssid:'hotspot',ip:state.ip,current_ssid:'home',partial_limit:10,mounted:true,audio_ready:true,storage_error:'',format_challenge:0,command_id:0,command_result:'',command_busy:false};
let requests=[],id=0;
const context=vm.createContext({document:{getElementById:el},TextEncoder,AbortSignal:{timeout:()=>null},setTimeout:()=>0,clearTimeout(){},fetch:async(path,options)=>{requests.push([path,options]);return {ok:true,status:200,json:async()=>options.method==='POST'?{id:++id,status:'queued'}:path==='/api/status'?state:path==='/api/settings'?settings:{base_url:'http://192.168.1.20:8000'}};}});
vm.runInContext(fs.readFileSync(new URL('../src/web/app.js',import.meta.url),'utf8'),context);
await el('settings-nav').click(); assert.equal(el('settings-panel').hidden,false);
assert.equal(el('server-url').disabled,false); assert.equal(el('save-server').disabled,true);
assert.equal(vm.runInContext("normalizeServerUrl('192.168.1.20')",context),'http://192.168.1.20:8080');
el('token').value='001234'; await el('access').submit({preventDefault(){}});
await el('settings-nav').click(); assert.equal(el('settings-panel').hidden,false);
assert.equal(el('home-ssid').value,'home');
el('home-ssid').value='edited'; el('home-password').value='synthetic123';
await vm.runInContext('refresh()',context); assert.equal(el('home-ssid').value,'edited'); assert.equal(el('home-password').value,'synthetic123');
await el('wifi-config').submit({preventDefault(){}});
assert.equal(requests.at(-1)[0],'/api/settings');
assert.equal(JSON.parse(requests.at(-1)[1].body).profiles[0].password,'synthetic123');
assert.equal(el('home-password').value,'','password is cleared immediately after submission');
state={...state,command_id:id,command_result:'ok'};
settings={...settings,command_id:id,command_result:'ok'};
await vm.runInContext('refresh()',context); assert.match(el('message').textContent,/not confirmed/i);
el('refresh-limit').value='20'; await el('display-config').submit({preventDefault(){}});
settings={...settings,partial_limit:20,command_id:id,command_result:'ok'}; state={...state,command_id:id};
await vm.runInContext('refresh()',context); assert.match(el('message').textContent,/saved/i);
await el('prepare-format').click(); state={...state,command_id:id}; settings={...settings,command_id:id,format_challenge:123};
await vm.runInContext('refresh()',context); assert.equal(el('format-confirm').hidden,false);
await el('cancel-format').click(); assert.equal(el('format-confirm').hidden,true);
const before=requests.length; await el('erase-storage').click(); assert.equal(requests.length,before,'Cancel removes local confirmation');
await el('disconnect').click(); assert.equal(el('home-ssid').value,''); assert.equal(el('storage-status').textContent,''); assert.equal(el('settings-panel').hidden,false);
console.log('PASS Settings navigation/auth/edit preservation/secret clearing/exact readback/display/Cancel/logout');
