import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const elements=new Map(), clicks=[]; const el=id=>{if(!elements.has(id))elements.set(id,{value:'',checked:false,textContent:'',dataset:{},hidden:false,disabled:false,children:[],appendChild(c){this.children.push(c)},setAttribute(){},focus(){},showModal(){this.open=true;},close(){this.open=false; if(this.closeEvent)this.closeEvent();},addEventListener(k,v){this[k === 'close' ? 'closeEvent' : k]=v;}}); return elements.get(id)};
let revoke=0, payloads=[];
const status={state:'idle',wifi:true,ip:'192.168.1.4',mounted:true,pending:0,command_busy:false,stopping:false,recovery:false,connecting:false};
const context=vm.createContext({document:{getElementById:el,createElement:tag=>({tag,textContent:'',dataset:{},children:[],appendChild(c){this.children.push(c)},focus(){},showModal(){this.open=true;},close(){this.open=false; if(this.closeEvent)this.closeEvent();},addEventListener(k,v){this[k === 'close' ? 'closeEvent' : k]=v;},click(){clicks.push(this.download)},remove(){}}),body:{appendChild(){}}},AbortSignal:{timeout:()=>null},URL:{createObjectURL:()=> 'blob:fixture',revokeObjectURL:()=>++revoke},setTimeout:fn=>{if(fn.name==='revokeDownload')fn();return 0},clearTimeout(){},fetch:async(path,options)=>{payloads.push([path,options]);return {ok:true,status:200,json:async()=>path==='/api/status'?status:path==='/api/notes'?{notes:[{id:'safe-note',audio:true,transcribed:false}]}:{base_url:'http://192.168.1.20:8080'},blob:async()=>({size:9000})}}});
vm.runInContext(fs.readFileSync(new URL('../src/web/app.js',import.meta.url),'utf8'),context);
el('token').value='001234'; await el('access').submit({preventDefault(){}});
assert.equal(el('note-list').children.length,1);
assert.equal(el('note-list').children[0].children[1].disabled,false);
await vm.runInContext("downloadNote('safe-note','audio')",context);
assert.equal(clicks.at(-1),'safe-note.wav'); assert.equal(revoke,1);
assert.equal(payloads.at(-1)[0],'/api/download/audio?id=safe-note');
assert.equal(payloads.at(-1)[1].headers.Authorization,'Bearer 001234');
const n=payloads.length; await vm.runInContext("downloadNote('../outside','audio')",context); assert.equal(payloads.length,n);
assert.equal(el('record').disabled,false);
context.fetch=async()=>{throw Error('offline')}; await vm.runInContext('refresh()',context);
assert.equal(el('note-list').children[0].children[1].disabled,true);
assert.equal(el('storage-gauge').hidden,true);
console.log('PASS bounded note list, safe ID download, bearer only header, blob attachment/revoke, controls restored');
