[platformio]
default_envs = waveshare_epaper_154_v2

[env:waveshare_epaper_154_v2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.embed_txtfiles =
  certs/README.txt
build_flags =
  -std=gnu++17
  -D CORE_DEBUG_LEVEL=3
monitor_filters = esp32_exception_decoder
